### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by ronilbhatia** [parisDreyer/fullstack#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments
* Add link to live page (placeholder for now)
* Missing links in the right sidebar - you need to make each page as an actual wiki page as opposed to just having them in the root directory of your git. I can show you how to do this if you are unsure.
---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
* Currently the formatting is not matching what was expected. Take a look at the bluebird wiki for an example of what it should look like.
  * Currently missing MVPs for user auth (both back-end and front-end - this MVP should come after Heroku but before your 4 core features) as well as your Production README (this one will be your last MVP)
  * Need time estimates for each of your MVPs
  * It is unclear what your CRUD action is here. I am guessing it will be asking questions (users can edit/delete their questions as well). Please make this clear in the MVP doc
  * For user auth and each of your core features, please list out the details of the features in bullets below each item. There should be a minimum 3 bullet points for each of these, here are examples of bullets that should work for just about any feature
    * Adequate Styling
    * Smooth, bug-free navigation
    * Adequate and appropriate seed data to demonstrate the feature
---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
* Missing 'Database Schema' header at top of file
* Again, look at bluebird to see example of how this should be formatted. In the 'details' column only need to specify 'foreign_key' not what table the foreign key references. This, along with indexing, should be laid out below the table in bullet points.
* If you are going to enforce uniqueness, you have to index - for example `email` column in `users` table
* Currently in your `votes` table you are enforcing uniqueness individually on the `answer_id`, `question_id` and `user_id` columns - this is problematic as it will allow each answer, question, and user to only exist in the table once. Instead you want to enforce some sort of combinatorial uniqueness, most likely `[:user_id, :answer_id], uniqueness: true`, and `[:user_id, :question_id], uniqueness: true`. We can discuss more. Also, `user_id` should probably have a not null constraint as well.
* Let's leave `category_id` as an optional field initially since this is a bonus feature. We don't want questions to have to rely on this initially as it could be an overwhelming amount to build out before seeing basic functionality.
* Don't forget `created_at` and `updated_at` for each column
---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
* The state, although it appears to be nested appropriately, is not formatted properly and makes it difficult to read. For instance, in glancing at the state shape it appears as though `comments` might be nested under `questions` or `answers` based on the indentation when in fact it is not.
* Add a sample state for comments and errors since these are part of your core MVPs. Not as concerned about the bonuses, but make sure you have an example of at least one item for each of the slices of state that represent part of your core functionality.
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
* Each item within the HTML  & API Endpoints section should be a bullet
* The majority of the answers and comments routes are superfluous and do not require such deep nesting. The only routes that should be nested are `index` routes where you may want to view all answers or comments for a given question, or all comments for a given answer. In this case the route must be nested, however for the CRUD actions you do not need to nest these routes (you can pass up relevant foreign keys via hidden inputs).
* Only the route itself needs to be backticked, not its description
* Don't need separate routes for question votes and answer votes - this again can be handled by hidden inputs.
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
* Need to add indentation to routes - as of right now the routes are unreadable.

**Comment by parisDreyer** [comment]
okay, I made all of the changes suggested --Tuesday October 9, 2018, 3:23PM
